import { RegionCardDataTypes } from 'types/home/search/SearchTypes';

export const locationData: RegionCardDataTypes[] = [
  { id: 1, title: '서울', subtitle: '서울특별시' },
  { id: 2, title: '마포', subtitle: '서울특별시' },
  { id: 3, title: '경기', subtitle: '경기도' },
  { id: 4, title: '인천', subtitle: '인천광역시' },
  { id: 5, title: '부산', subtitle: '부산광역시' },
  { id: 6, title: '대구', subtitle: '대구광역시' },
  { id: 7, title: '대전', subtitle: '대전광역시' },
  { id: 8, title: '광주', subtitle: '광주광역시' },
  { id: 9, title: '울산', subtitle: '울산광역시' },
  { id: 10, title: '세종', subtitle: '세종특별자치' },
  { id: 11, title: '충청도' },
  { id: 12, title: '전라도' },
  { id: 13, title: '경상도' },
  { id: 14, title: '강원도' },
  { id: 15, title: '제주도', subtitle: '제주특별자치도' },
  { id: 16, title: '종로', subtitle: '서울 종로구' },
  { id: 17, title: '송파', subtitle: '서울특별시' },
  { id: 18, title: '화성시', subtitle: '경기도' },
  { id: 19, title: '안산시', subtitle: '경기도' },
  { id: 20, title: '창원시', subtitle: '경상남도' },
  { id: 21, title: '달성군', subtitle: '대구광역시' },
  { id: 22, title: '천안', subtitle: '충청남도' },
  { id: 23, title: '평택', subtitle: '경기도' },
  { id: 24, title: '광진구', subtitle: '서우륵별시' },
  { id: 25, title: '파주', subtitle: '경기도' },
  { id: 26, title: '김해', subtitle: '경상남도' },
  { id: 27, title: '용인', subtitle: '경기도' },
  { id: 28, title: '강남', subtitle: '서울특별시' },
  { id: 29, title: '노원', subtitle: '서울특별시' },
  { id: 30, title: '용산', subtitle: '서울특별시' },
];
